const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const W = canvas.width, H = canvas.height;
const ui = {
  score: document.querySelector('#score'), best: document.querySelector('#best'), state: document.querySelector('#state'), led: document.querySelector('#led'),
  control: document.querySelector('#control-status'), overlay: document.querySelector('#overlay'), start: document.querySelector('#start'), bloom: document.querySelector('#bloom'), message: document.querySelector('#message'), day: document.querySelector('#day'), combo: document.querySelector('#combo'), route: document.querySelector('#route'), map: document.querySelector('#level-map')
};
let best = Number(localStorage.getItem('petal-post-best') || 0);
const levels=[
  {name:'LILY LANE',goal:5,speed:1.7,kinds:['seal'],note:'Learn the wax seal.'},
  {name:'MOON GARDEN',goal:7,speed:2.05,kinds:['seal','seal','express'],note:'Express mail arrives.'},
  {name:'TULIP TEA ROOM',goal:9,speed:2.38,kinds:['seal','express','ribbon'],note:'Ribbon parcels join the shift.'},
  {name:'CLOUD COTTAGE',goal:11,speed:2.72,kinds:['seal','express','ribbon','ribbon'],note:'A fast afternoon route.'},
  {name:'GOLDEN GREENHOUSE',goal:13,speed:3.05,kinds:['seal','express','ribbon','seal','ribbon'],note:'The master postie test.'}
];
let unlocked=Math.min(5,Number(localStorage.getItem('petal-press-unlocked')||1)), selectedLevel=1;
let playing = false, buttonDown = false, pressed = false, inputLocked = false, score = 0, combo = 0, frame = 0, last = 0, speed = 2.25, audio, ambienceTimer, ambienceStep = 0;
let letters = [], petals = [], lives = 3, seal = 0, sealing = false, current = null;
ui.best.textContent = String(best).padStart(3,'0');

function tone(freq, duration=.07, type='square', vol=.045, when=0) { if (!audio) return; const o=audio.createOscillator(), g=audio.createGain(), at=audio.currentTime+when; o.type=type; o.frequency.value=freq; g.gain.setValueAtTime(vol,at); g.gain.exponentialRampToValueAtTime(.001,at+duration); o.connect(g).connect(audio.destination); o.start(at); o.stop(at+duration); }
function noise(duration=.08,vol=.012,when=0){if(!audio)return;const size=Math.floor(audio.sampleRate*duration),buffer=audio.createBuffer(1,size,audio.sampleRate),data=buffer.getChannelData(0),source=audio.createBufferSource(),gain=audio.createGain(),at=audio.currentTime+when;for(let i=0;i<size;i++)data[i]=(Math.random()*2-1)*(1-i/size);source.buffer=buffer;gain.gain.value=vol;source.connect(gain).connect(audio.destination);source.start(at);}
function startAmbience(){clearInterval(ambienceTimer);ambienceStep=0;const roots=[130.81,146.83,164.81,196], jazzBar=()=>{const root=roots[ambienceStep%roots.length],minor=ambienceStep===1; tone(root,.68,'triangle',.052);[1.25,minor?1.498:1.5,minor?1.782:1.875].forEach((ratio,i)=>tone(root*ratio,.72,'sine',.018,.04+i*.015));tone(root*2,.17,'sine',.022,.46);noise(.05,.009,.12);noise(.045,.006,.59);ambienceStep++;};jazzBar();ambienceTimer=setInterval(jazzBar,1080);}
function stopAmbience(){clearInterval(ambienceTimer); ambienceTimer=null;}
function setState(s) { ui.state.textContent=s; ui.control.textContent=s; const colors={PRESSED:'#d94b95',HELD:'#dbe780',RELEASED:'#b7c9ec',READY:'#aaa',OUCH:'#f46d6d'}; ui.led.style.background=colors[s]||'#aaa'; }
function renderMap(){ui.map.innerHTML='<span class="map-label">GARDEN ROUTE MAP</span>'+[...Array(8)].map((_,i)=>{const n=i+1,open=n<=unlocked&&n<=5;return `<button class="level-button ${n===selectedLevel?'selected':''} ${open?'':'locked'}" data-level="${n}" ${open?'':'disabled'}>${open?`0${n}`:'🔒'}</button>`}).join('');ui.map.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>{selectedLevel=Number(b.dataset.level);renderMap();ui.start.textContent=`START LEVEL ${selectedLevel}`;}));}
function reset() { const level=levels[selectedLevel-1];score=0; combo=0; frame=0; speed=level.speed; lives=3; seal=0; sealing=false; current=null; letters=[]; petals=[]; ui.score.textContent='000';ui.combo.textContent='×0'; ui.day.textContent=`LEVEL ${String(selectedLevel).padStart(2,'0')} • 0/${level.goal}`; ui.message.textContent=level.note.toUpperCase(); spawnLetter(610); }
function startGame() { if (!audio) audio=new (window.AudioContext||window.webkitAudioContext)(); audio.resume(); reset(); startAmbience(); playing=true; ui.overlay.classList.add('hidden'); setState('RELEASED'); tone(523,.1,'triangle',.06);tone(659,.15,'triangle',.05,.1); }
function endGame() { playing=false; buttonDown=false; sealing=false;stopAmbience(); setState('OUCH'); tone(110,.3,'sawtooth',.035); setTimeout(()=>{ui.overlay.classList.remove('hidden'); ui.overlay.querySelector('h1').textContent='MAILROOM CLOSED'; ui.overlay.querySelector('p').textContent=`You sealed ${score} letter${score===1?'':'s'}!`; ui.start.textContent='OPEN AGAIN';},350); if(score>best){best=score;localStorage.setItem('petal-post-best',best);ui.best.textContent=String(best).padStart(3,'0');} }
function spawnLetter(x) { const level=levels[selectedLevel-1], routes=['LILY LANE','MOON GARDEN','CLOUD COTTAGE','TULIP TEA ROOM','BUTTERCUP BAY']; const bonus=combo>0&&combo%3===0; const kind=bonus?'seal':level.kinds[Math.floor(Math.random()*level.kinds.length)], route=bonus?'GOLDEN GREENHOUSE':routes[Math.floor(Math.random()*routes.length)], task={seal:'1/3 CHECK • 2/3 WAX • 3/3 SEND',express:'1/3 CHECK • 2/3 TAP • 3/3 SEND',ribbon:'1/3 CHECK • 2/3 TUG • 3/3 SEND'}[kind]; ui.route.textContent=`${task} • ${route}`; letters.push({x, target:bonus?55:42+Math.random()*37, stamp:0, active:false, released:false, done:false, bonus, kind, taps:0, announced:false, route, color:bonus?'#f5cf65':['#f8c4d6','#dbe780','#b7c9ec'][Math.floor(Math.random()*3)]}); }
function completeLevel(){playing=false;buttonDown=false;stopAmbience();const finished=selectedLevel;unlocked=Math.min(5,Math.max(unlocked,finished+1));localStorage.setItem('petal-press-unlocked',unlocked);ui.overlay.querySelector('h1').textContent=`LEVEL ${finished} COMPLETE!`;ui.overlay.querySelector('p').textContent=`${levels[finished-1].name}: ${score} letters sealed.`;ui.start.textContent=finished<5?`START LEVEL ${finished+1}`:'REPLAY LEVEL 5';if(finished<5)selectedLevel=finished+1;renderMap();ui.overlay.classList.remove('hidden');setState('READY');tone(1046,.18,'triangle',.06);tone(1318,.4,'sine',.04,.12);}
function succeed(l){l.done=true;const reward=l.bonus?2:1;score+=reward;combo++;speed+=.065;ui.score.textContent=String(score).padStart(3,'0');ui.combo.textContent=`×${combo}`;const level=levels[selectedLevel-1];ui.day.textContent=`LEVEL ${String(selectedLevel).padStart(2,'0')} • ${Math.min(score,level.goal)}/${level.goal}`;ui.message.textContent=l.bonus?'GOLDEN SEAL! +2':l.kind==='ribbon'?'RIBBON READY!':l.kind==='express'?'EXPRESS AWAY!':'PERFECT SEAL!';tone(740,.12,'triangle',.065);tone(1110,.32,'sine',.04,.09);burst();current=null;sealing=false;if(score>=level.goal)completeLevel();}
function fail(l,message){l.done=true;lives--;combo=0;ui.combo.textContent='×0';ui.message.textContent=message;tone(180,.12,'sawtooth');current=null;sealing=false;}
function inputDown(e) { if(e) e.preventDefault(); if (!playing || buttonDown || inputLocked) return; buttonDown=true; pressed=true; ui.bloom.classList.add('active'); setState('PRESSED'); tone(310,.05,'square',.06); if(current&&current.active&&!current.done){if(current.kind==='express'){inputLocked=true;ui.message.textContent='STEP 2/3 EXPRESS STAMPED!';tone(600,.08,'triangle',.055);succeed(current);setTimeout(()=>inputLocked=false,160);}if(current.kind==='ribbon'){current.taps++;ui.message.textContent=`STEP 2/3 RIBBON TUG ${current.taps}/2`;tone(510,.06,'triangle',.055);}} }
function inputUp(e) { if(e) e.preventDefault(); if (!playing || !buttonDown) return; buttonDown=false; ui.bloom.classList.remove('active'); setState('RELEASED'); if(inputLocked) return; if(current && current.active && current.kind==='seal' && !current.released){current.released=true;const accurate=Math.abs(current.stamp-current.target)<12;accurate?succeed(current):fail(current,'WAX WASN’T READY!');} }
ui.start.addEventListener('click', startGame); ui.bloom.addEventListener('pointerdown',e=>{e.currentTarget.setPointerCapture?.(e.pointerId);inputDown(e)}); ui.bloom.addEventListener('pointerup',inputUp); window.addEventListener('pointerup',inputUp); window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat) inputDown(e);}); window.addEventListener('keyup',e=>{if(e.code==='Space')inputUp(e);});

function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h)}
function cloud(x,y,s){ctx.fillStyle='#fff9e8'; [[0,10,42,22],[18,0,35,32],[42,10,48,22]].forEach(a=>ctx.fillRect(x+a[0]*s,y+a[1]*s,a[2]*s,a[3]*s));}
function drawMailroom(){rect(0,0,W,H,'#b6dcea');cloud(64,52,.7);cloud(535,62,.8);rect(0,315,W,165,'#f8e5c5');rect(0,315,W,9,'#e5b98d'); // wall art
rect(58,125,105,95,'#fff9e8');rect(62,129,97,87,'#8cb9b4');rect(68,177,85,35,'#94c47a');cloud(77,146,.45);rect(510,115,124,108,'#fff9e8');rect(514,119,116,100,'#f5c5d9');rect(535,145,75,45,'#dbe780');
// conveyor
rect(0,342,W,67,'#76506d');rect(0,350,W,51,'#9c8aab');for(let x=-20;x<W;x+=45){rect(x,354,28,9,'#c4b6cc');rect(x,387,28,9,'#c4b6cc');}rect(0,405,W,8,'#542c4d'); // desk
rect(218,277,210,13,'#9c6a60');rect(229,290,12,62,'#9c6a60');rect(405,290,12,62,'#9c6a60');}
function drawPress(){const x=323,y=238;rect(x-34,y+49,68,13,'#542c4d');rect(x-28,y+42,56,10,'#d94b95');rect(x-10,y-7,20,50,'#7b668e');rect(x-31,y-18,62,13,'#542c4d');rect(x-25,y-14,50,7,'#f5b6d3');rect(x-6,y+9,12,16,'#dbe780');ctx.fillStyle=buttonDown?'#d94b95':'#f4a5c8';ctx.fillRect(x-17,y+25,34,12);ctx.fillStyle='#542c4d';ctx.fillRect(x-4,y+29,8,5);}
function drawLetter(l){const x=Math.round(l.x),y=357;rect(x,y,86,35,'#542c4d');rect(x+3,y+3,80,29,'#fff9e8');rect(x+6,y+6,74,23,l.color);rect(x+10,y+10,35,3,'#fff9e8');rect(x+10,y+17,50,3,'#fff9e8');ctx.fillStyle='#542c4d';ctx.font='11px Pixelify Sans';ctx.fillText(l.kind==='express'?'⚡':l.kind==='ribbon'?'♧':'✿',x+62,y+23);if(l.active&&l.kind==='seal'){ctx.strokeStyle='#542c4d';ctx.lineWidth=3;ctx.strokeRect(x+10,y-18,64,8);rect(x+12,y-16,Math.min(60,l.stamp*60/l.target),4,'#d94b95');rect(x+10,y-31,64,8,'#fff9e8');rect(x+12,y-29,l.target,4,'#dbe780');ctx.font='11px Pixelify Sans';ctx.fillStyle='#fff9e8';ctx.fillText('HOLD → RELEASE',x-6,y-37);}else if(l.active){ctx.fillStyle='#fff9e8';ctx.font='14px Pixelify Sans';ctx.fillText(l.kind==='express'?'PRESS!':`${l.taps}/2 TUGS`,x+8,y-14);}}
function burst(){for(let i=0;i<9;i++)petals.push({x:350,y:285,vx:(Math.random()-.5)*3,vy:-Math.random()*2,life:23});}
function update(dt){if(!playing)return;frame+=dt;letters.forEach(l=>{l.x-=speed*dt;if(l.x<370&&l.x+86>323&&!l.done){l.active=true;current=l;if(!l.announced){ui.message.textContent=l.kind==='express'?'EXPRESS! TAP ONCE':l.kind==='ribbon'?'RIBBON! TAP TWICE':'WAX SEAL: HOLD + RELEASE';l.announced=true;}if(buttonDown&&l.kind==='seal'){l.stamp=Math.min(100,l.stamp+1.05*dt);sealing=true;setState(pressed?'PRESSED':'HELD');if(Math.floor(frame/7)!==Math.floor((frame-dt)/7))tone(405,.025,'sine',.014);}pressed=false;}else if(l.active&&!l.done&&l.x+86<=323){if(l.kind==='ribbon'&&l.taps===2)succeed(l);else fail(l,l.kind==='ribbon'?'RIBBON NEEDS TWO TUGS!':'MISSED THE PRESS!');}});if(letters.length&&letters[0].x<-110){letters.shift();if(lives<=0)endGame();else spawnLetter(720);}petals.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});petals=petals.filter(p=>p.life>0);}
function render(){drawMailroom();drawPress();letters.forEach(drawLetter);petals.forEach(p=>rect(p.x,p.y,4,4,'#e891bb'));ctx.fillStyle='#542c4d';ctx.font='18px Pixelify Sans';ctx.fillText('LIVES  '+ '♥ '.repeat(lives)+'♡ '.repeat(3-lives),18,452);ctx.fillText('WAX SEAL STATION',260,245);}
function loop(t){let dt=Math.min((t-last)/16.67,2);last=t;update(dt);render();requestAnimationFrame(loop)} renderMap(); requestAnimationFrame(loop); setState('READY');
