const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),W=720,H=480;
const ui={score:$('#score'),best:$('#best'),state:$('#state'),led:$('#led'),control:$('#control-status'),overlay:$('#overlay'),start:$('#start'),bloom:$('#bloom'),message:$('#message'),day:$('#day'),combo:$('#combo'),route:$('#route'),map:$('#level-map')};function $(s){return document.querySelector(s)}
const levels=[['LILY LANE',3,1,'Learn three stations.'],['MOON GARDEN',4,1.22,'Carousel turns faster.'],['TULIP TEA ROOM',5,1.45,'Wax targets tighten.'],['CLOUD COTTAGE',6,1.7,'Dispatch is in a hurry.'],['GOLDEN GREENHOUSE',7,2,'Master postie test.']],seals=['✿','★','☾','♥'],routes=['LILY LANE','MOON GARDEN','TULIP TEA ROOM','CLOUD COTTAGE','BUTTERCUP BAY'];
let best=+localStorage.getItem('petal-post-best')||0,unlocked=Math.min(5,+localStorage.getItem('petal-press-unlocked')||1),selectedLevel=1,playing=false,down=false,score=0,lives=3,combo=0,stage=0,time=0,last=0,pack=0,current,next=0,audio,nodes=[],music,petals=[];ui.best.textContent=String(best).padStart(3,'0');
function tone(f,d=.08,t='triangle',v=.05,delay=0){if(!audio)return;let a=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=t;o.frequency.setValueAtTime(f,a);g.gain.setValueAtTime(v,a);g.gain.exponentialRampToValueAtTime(.001,a+d);o.connect(g).connect(audio.destination);o.start(a);o.stop(a+d)}
function sfx(n){if(n==='stamp'){tone(310,.07,'square',.065);tone(620,.09,'triangle',.035,.035)}if(n==='wax'){tone(220,.12,'sine',.04)}if(n==='send'){tone(660,.12,'triangle',.07);tone(880,.3,'sine',.045,.1)}if(n==='bad')tone(155,.18,'sawtooth',.055);if(n==='win'){tone(784,.14,'triangle',.07);tone(1046,.35,'sine',.05,.12)}}
function startMusic(){stopMusic();let master=audio.createGain();master.gain.value=.1;master.connect(audio.destination);let ratios=[1,1.25,1.5,1.875],roots=[130.81,164.81,196,146.83],bar=0;ratios.forEach((r,i)=>{let o=audio.createOscillator(),g=audio.createGain();o.type=i?'sine':'triangle';o.frequency.value=roots[0]*r;g.gain.value=i?.07:.24;o.connect(g).connect(master);o.start();nodes.push(o)});music=setInterval(()=>{let root=roots[++bar%4];nodes.forEach((o,i)=>o.frequency.setTargetAtTime(root*ratios[i],audio.currentTime,.65))},3600)}function stopMusic(){clearInterval(music);nodes.forEach(o=>{try{o.stop()}catch{}});nodes=[]}
function state(s){ui.state.textContent=ui.control.textContent=s;ui.led.style.background=({PRESSED:'#d94b95',HELD:'#dbe780',RELEASED:'#b7c9ec',READY:'#aaa',OUCH:'#f46d6d'})[s]||'#aaa'}
function map(){ui.map.innerHTML='<span class="map-label">GARDEN ROUTE MAP</span>'+[...Array(8)].map((_,i)=>{let n=i+1,ok=n<=unlocked&&n<=5;return `<button class="level-button ${n===selectedLevel?'selected':''} ${ok?'':'locked'}" data-level="${n}" ${ok?'':'disabled'}>${ok?'0'+n:'🔒'}</button>`}).join('');ui.map.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{selectedLevel=+b.dataset.level;map();ui.start.textContent=`START LEVEL ${selectedLevel}`})}
function levelText(){let l=levels[selectedLevel-1];ui.day.textContent=`LEVEL 0${selectedLevel} • ${score}/${l[1]}`}function newPack(){stage=0;time=0;down=false;pack++;current={seal:seals[~~(Math.random()*4)],wax:44+Math.random()*25,fill:0,carousel:0,waxing:false,armed:false,train:0,route:routes[~~(Math.random()*5)]};ui.route.textContent=`PACKAGE ${String(pack).padStart(2,'0')} • ${current.route}`;ui.message.textContent='1/3  MATCH THE STAMP'}
function start(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();audio.resume();score=lives=0;score=0;lives=3;combo=pack=0;petals=[];ui.score.textContent='000';ui.combo.textContent='×0';levelText();newPack();startMusic();playing=true;ui.overlay.classList.add('hidden');state('RELEASED')}
function close(){playing=false;stopMusic();state('OUCH');sfx('bad');if(score>best){best=score;localStorage.setItem('petal-post-best',best);ui.best.textContent=String(best).padStart(3,'0')}setTimeout(()=>{ui.overlay.querySelector('h1').textContent='MAILROOM CLOSED';ui.overlay.querySelector('p').textContent=`You completed ${score} package${score===1?'':'s'}.`;ui.start.textContent='TRY THIS LEVEL AGAIN';ui.overlay.classList.remove('hidden')},250)}
function win(){playing=false;stopMusic();let done=selectedLevel;unlocked=Math.min(5,Math.max(unlocked,done+1));localStorage.setItem('petal-press-unlocked',unlocked);if(done<5)selectedLevel++;map();ui.overlay.querySelector('h1').textContent=`LEVEL ${done} COMPLETE!`;ui.overlay.querySelector('p').textContent=`All ${levels[done-1][1]} packages reached their gardens.`;ui.start.textContent=done<5?`START LEVEL ${done+1}`:'REPLAY LEVEL 5';ui.overlay.classList.remove('hidden');state('READY');sfx('win')}
function fail(msg){lives--;combo=0;ui.combo.textContent='×0';ui.message.textContent=msg;state('OUCH');sfx('bad');next=.75}function done(){score++;combo++;ui.score.textContent=String(score).padStart(3,'0');ui.combo.textContent=`×${combo}`;levelText();petals.push(...Array.from({length:14},()=>({x:362,y:222,vx:(Math.random()-.5)*5,vy:-Math.random()*4,life:32})));sfx('send');if(score>=levels[selectedLevel-1][1])win();else{ui.message.textContent='PACKAGE SENT!';next=.8}}
function press(){if(!playing||next)return;down=true;state('PRESSED');if(stage===0){if(seals[current.carousel]===current.seal){stage=1;time=0;ui.message.textContent='GREAT!  2/3 HOLD TO POUR WAX';sfx('stamp')}else{ui.message.textContent=`WAIT FOR ${current.seal} — NO PENALTY`;tone(260,.05,'sine',.02)}}else if(stage===1){current.fill=0;current.waxing=true;sfx('wax')}else{current.armed=true;ui.message.textContent='3/3 RELEASE ON GREEN PLATFORM'}}function release(){if(!playing||!down)return;down=false;state('RELEASED');if(stage===1&&current.waxing){current.waxing=false;Math.abs(current.fill-current.wax)<10?(stage=2,time=0,ui.message.textContent='3/3 PRESS, THEN RELEASE ON GREEN',sfx('stamp')):fail('WAX MISSED THE MARK')}else if(stage===2&&current.armed){Math.abs(current.train-50)<13?done():fail('TRAIN LEFT WITHOUT THE PARCEL')}}
ui.start.onclick=start;ui.bloom.addEventListener('pointerdown',e=>{e.preventDefault();e.currentTarget.setPointerCapture?.(e.pointerId);press()});ui.bloom.addEventListener('pointerup',release);window.addEventListener('pointerup',release);window.onkeydown=e=>{if(e.code==='Space'&&!e.repeat){e.preventDefault();press()}};window.onkeyup=e=>{if(e.code==='Space'){e.preventDefault();release()}};
function r(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(~~x,~~y,w,h)}function cloud(x,y,s){ctx.fillStyle='#fff9e8';[[0,10,42,22],[18,0,35,32],[42,10,48,22]].forEach(a=>ctx.fillRect(x+a[0]*s,y+a[1]*s,a[2]*s,a[3]*s))}function room(){r(0,0,W,H,'#b6dcea');cloud(50,65,.8);cloud(550,80,.75);r(0,310,W,170,'#f8e5c5');r(0,310,W,9,'#e5b98d');r(0,413,W,67,'#76506d');r(0,421,W,51,'#9c8aab');for(let x=-20;x<W;x+=45){r(x,425,28,9,'#c4b6cc');r(x,458,28,9,'#c4b6cc')}}function panel(x,y,w,h,t,a){r(x+4,y+4,w,h,'#7b668e');r(x,y,w,h,a?'#fff9e8':'#e3d9e6');r(x,y,w,24,a?'#d94b95':'#9c8aab');ctx.fillStyle=a?'#fff':'#542c4d';ctx.font='15px Pixelify Sans';ctx.fillText(t,x+9,y+17)}
function stations(){panel(38,235,195,145,'1 • STAMP MATCH',stage===0);panel(263,235,195,145,'2 • WAX SEAL',stage===1);panel(488,235,195,145,'3 • DISPATCH',stage===2);ctx.font='34px Pixelify Sans';if(stage===0){for(let i=0;i<4;i++){let x=55+i*42;r(x,281,34,38,i===current.carousel?'#dbe780':'#f5c5d9');ctx.fillStyle='#542c4d';ctx.fillText(seals[i],x+6,312)}ctx.font='14px Pixelify Sans';ctx.fillText(`NEED: ${current.seal}`,71,348);if(seals[current.carousel]===current.seal){ctx.fillStyle='#d94b95';ctx.fillText('BLOOM NOW!',66,368)}}else{ctx.fillStyle='#542c4d';ctx.fillText(current.seal,133,319)}if(stage===1){r(284,302,152,18,'#542c4d');r(288,306,144,10,'#fff9e8');r(288+current.wax*1.44,306,13,10,'#dbe780');r(288,306,current.fill*1.44,10,'#d94b95');ctx.font='13px Pixelify Sans';ctx.fillStyle='#542c4d';ctx.fillText('HOLD, THEN RELEASE',290,348)}else{ctx.font='30px Pixelify Sans';ctx.fillStyle='#542c4d';ctx.fillText('✿',344,322)}if(stage===2){r(509,323,152,15,'#542c4d');r(546,327,38,7,'#dbe780');r(513+current.train*1.4,290,24,25,current.armed?'#d94b95':'#f5c5d9');ctx.font='22px Pixelify Sans';ctx.fillStyle='#542c4d';ctx.fillText('✉',516+current.train*1.4,310);ctx.font='13px Pixelify Sans';ctx.fillText(current.armed?'RELEASE ON GREEN!':'PRESS TO LOAD',513,348)}else{ctx.font='30px Pixelify Sans';ctx.fillText('✉',566,322)}}
function update(dt){if(!playing)return;if(next){next-=dt;if(next<=0)lives<=0?close():newPack();return}time+=dt;let speed=levels[selectedLevel-1][2];if(stage===0)current.carousel=~~(time*speed*1.5)%4;if(stage===1&&down){current.fill=Math.min(100,current.fill+speed*28*dt);state('HELD')}if(stage===2)current.train=(Math.sin(time*speed*2.2)+1)*50;petals.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});petals=petals.filter(p=>p.life>0)}function render(){room();if(current)stations();petals.forEach(p=>r(p.x,p.y,4,4,'#e891bb'));ctx.fillStyle='#542c4d';ctx.font='17px Pixelify Sans';ctx.fillText('LIVES  '+'♥ '.repeat(lives)+'♡ '.repeat(3-lives),18,452);ctx.font='14px Pixelify Sans';ctx.fillText('POSTCARD ASSEMBLY LINE',274,205)}function loop(t){let dt=Math.min((t-last)/16.67,2);last=t;update(dt);render();requestAnimationFrame(loop)}map();state('READY');requestAnimationFrame(loop);
